/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.Data;
import backend.Endereco;
import backend.Ingrediente;
import backend.MateriaPrima;
import backend.Produto;
import backend.Manufatura;
import backend.Processo;
import backend.Operador;
import backend.Equipamento;
import backend.Pedido;
import backend.Pessoa;
import java.util.ArrayList;
import java.time.LocalDate;
import javax.swing.JOptionPane;





/**
 *
 * @author robo
 */
public class CadastrarProduto extends javax.swing.JFrame {
    //Instanciando todas as Arrays
    ArrayList<Ingrediente> listaIngrediente;
    ArrayList<Manufatura> listaManufatura;
    ArrayList<Pedido> listaPedidos;
    ArrayList<Produto> listaProdutos;
    


    /**
     * Creates new form CadastrarProduto
     */
    
    //Construtores que seram chamados pelas outras classes (interfaces) 
    public CadastrarProduto() {
        initComponents();
    }
    
    public CadastrarProduto(ArrayList<Pedido> listaPedidos, ArrayList<Produto> listaProdutos){
        this.listaPedidos = listaPedidos;
        this.listaProdutos = listaProdutos;
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtCustoDoProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIngredienteNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIngredienteUnidade = new javax.swing.JTextField();
        txtIngredientePreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIngredienteFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIngredienteQuant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bttIngredCad = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIngredienteCusto = new javax.swing.JTextField();
        txtIngredienteCalc = new javax.swing.JButton();
        lblIngredienteCadastroSucess = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtManufaturaProcesso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtManufaturaCusto = new javax.swing.JTextField();
        bttManufaturaCadastrar = new javax.swing.JButton();
        bttCalcular = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtManufaturaHoras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtManufaturaCustoTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtOpNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtOpDiaNasc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtOpMesNasc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtOpAnoNasc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtOpIdade = new javax.swing.JTextField();
        txtOpCPF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtEnderecoEstado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEnderecoBairro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEnderecoNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtEnderecoCidade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEnderecoRua = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSalarioPorHora = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtClienteDiaNasc1 = new javax.swing.JTextField();
        txtClienteMesNasc1 = new javax.swing.JTextField();
        txtClienteAnoNasc1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtDepreciacao = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        lblManufaturaCadastroSucess = new javax.swing.JLabel();
        bttVoltar = new javax.swing.JButton();
        bttCadastrarProduto = new javax.swing.JButton();
        bttCadastrarProduto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produto");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCustoDoProduto.setEditable(false);
        txtCustoDoProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtCustoDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoDoProdutoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrediente"));

        jLabel3.setText("Nome:");

        txtIngredienteNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIngredienteNomeFocusGained(evt);
            }
        });
        txtIngredienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidade:");

        txtIngredienteUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteUnidadeActionPerformed(evt);
            }
        });

        txtIngredientePreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredientePrecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço:");

        txtIngredienteFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteFornecedorActionPerformed(evt);
            }
        });

        jLabel6.setText("Fornecedor:");

        txtIngredienteQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteQuantActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade:");

        bttIngredCad.setText("Cadastrar");
        bttIngredCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIngredCadActionPerformed(evt);
            }
        });

        jLabel10.setText("Custo do ingrediente:");

        txtIngredienteCusto.setEditable(false);
        txtIngredienteCusto.setBackground(new java.awt.Color(153, 153, 153));

        txtIngredienteCalc.setText("Calcular");
        txtIngredienteCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteCalcActionPerformed(evt);
            }
        });

        lblIngredienteCadastroSucess.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIngredienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(298, 298, 298))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtIngredienteCalc)
                                .addGap(180, 180, 180)
                                .addComponent(lblIngredienteCadastroSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtIngredientePreco))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIngredienteUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttIngredCad)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(65, 65, 65))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIngredienteQuant, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtIngredienteCusto)
                                    .addComponent(txtIngredienteFornecedor))))))
                .addGap(153, 153, 153))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngredienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtIngredienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngredienteUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIngredienteQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIngredientePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtIngredienteCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttIngredCad)
                    .addComponent(txtIngredienteCalc)
                    .addComponent(lblIngredienteCadastroSucess))
                .addContainerGap())
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("Custo do produto:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Manufatura"));

        jLabel8.setText("Processo:");

        txtManufaturaProcesso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtManufaturaProcessoFocusGained(evt);
            }
        });
        txtManufaturaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufaturaProcessoActionPerformed(evt);
            }
        });

        jLabel9.setText("Custo por hora:");

        txtManufaturaCusto.setEditable(false);
        txtManufaturaCusto.setBackground(new java.awt.Color(153, 153, 153));

        bttManufaturaCadastrar.setText("Cadastrar");
        bttManufaturaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttManufaturaCadastrarActionPerformed(evt);
            }
        });

        bttCalcular.setText("Calcular");
        bttCalcular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bttCalcularFocusLost(evt);
            }
        });
        bttCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCalcularActionPerformed(evt);
            }
        });

        jLabel11.setText("Horas:");

        txtManufaturaHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufaturaHorasActionPerformed(evt);
            }
        });

        jLabel12.setText("Custo total:");

        txtManufaturaCustoTotal.setEditable(false);
        txtManufaturaCustoTotal.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operador"));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpNomeActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de nasc.:");

        txtOpDiaNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpDiaNascActionPerformed(evt);
            }
        });

        jLabel14.setText("/");

        jLabel15.setText("/");

        txtOpAnoNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOpAnoNascFocusLost(evt);
            }
        });
        txtOpAnoNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpAnoNascActionPerformed(evt);
            }
        });

        jLabel16.setText("Nome:");

        jLabel17.setText("Idade:");

        txtOpIdade.setEditable(false);
        txtOpIdade.setBackground(new java.awt.Color(153, 153, 153));
        txtOpIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpIdadeActionPerformed(evt);
            }
        });

        txtOpCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpCPFActionPerformed(evt);
            }
        });

        jLabel18.setText("CPF:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpIdade))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtOpMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtOpAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtOpIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Dados Pessoais");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtEnderecoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoEstadoActionPerformed(evt);
            }
        });

        jLabel20.setText("Bairro:");

        jLabel21.setText("Estado:");

        txtEnderecoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoNumeroActionPerformed(evt);
            }
        });

        jLabel22.setText("Número:");

        txtEnderecoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoCidadeActionPerformed(evt);
            }
        });

        jLabel23.setText("Cidade");

        txtEnderecoRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoRuaActionPerformed(evt);
            }
        });

        jLabel24.setText("Rua:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEnderecoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtEnderecoBairro)
                    .addComponent(txtEnderecoEstado))
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEnderecoCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtEnderecoRua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnderecoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnderecoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Endereço");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        jLabel26.setText("Cargo");

        jLabel27.setText("Salário por hora: ");

        txtSalarioPorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioPorHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalarioPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(txtSalarioPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamento"));

        txtClienteDiaNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteDiaNasc1ActionPerformed(evt);
            }
        });

        txtClienteAnoNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteAnoNasc1ActionPerformed(evt);
            }
        });

        jLabel28.setText("/");

        jLabel29.setText("/");

        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Depreciação");

        jLabel31.setText("Nome:");

        txtDepreciacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepreciacaoActionPerformed(evt);
            }
        });

        jLabel32.setText("Fabricante:");

        txtFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabricanteActionPerformed(evt);
            }
        });

        jLabel33.setText("Data de fabricação:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteDiaNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteMesNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteAnoNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteDiaNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel29)
                    .addComponent(txtClienteMesNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtClienteAnoNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepreciacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(96, 96, 96))
        );

        lblManufaturaCadastroSucess.setBackground(new java.awt.Color(0, 153, 0));
        lblManufaturaCadastroSucess.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtManufaturaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtManufaturaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bttCalcular)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManufaturaCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufaturaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bttManufaturaCadastrar)
                                .addGap(38, 38, 38)
                                .addComponent(lblManufaturaCadastroSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufaturaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufaturaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtManufaturaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtManufaturaCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCalcular)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblManufaturaCadastroSucess)
                        .addComponent(bttManufaturaCadastrar)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bttVoltar.setText("Voltar");
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        bttCadastrarProduto.setText("Cadastrar Produto");
        bttCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarProdutoActionPerformed(evt);
            }
        });

        bttCadastrarProduto1.setText("Calcular");
        bttCadastrarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarProduto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(bttVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttCadastrarProduto1)
                .addGap(18, 18, 18)
                .addComponent(bttCadastrarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVoltar)
                    .addComponent(bttCadastrarProduto)
                    .addComponent(bttCadastrarProduto1))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIngredienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteNomeActionPerformed
    }//GEN-LAST:event_txtIngredienteNomeActionPerformed

    private void txtIngredienteUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteUnidadeActionPerformed
    }//GEN-LAST:event_txtIngredienteUnidadeActionPerformed

    private void txtIngredientePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredientePrecoActionPerformed
    }//GEN-LAST:event_txtIngredientePrecoActionPerformed

    private void txtIngredienteFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteFornecedorActionPerformed
    }//GEN-LAST:event_txtIngredienteFornecedorActionPerformed

    private void txtIngredienteQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteQuantActionPerformed
    }//GEN-LAST:event_txtIngredienteQuantActionPerformed

    private void txtManufaturaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufaturaProcessoActionPerformed
        
    }//GEN-LAST:event_txtManufaturaProcessoActionPerformed

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        //Caso a pessoa clique no botão voltar
        //Mudando de uma interface gráfica para outra (CadastrarProduto -> Cadastrar), passando as duas listas
        new Cadastrar(this.listaPedidos,this.listaProdutos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttVoltarActionPerformed

    private void bttIngredCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIngredCadActionPerformed
        //Caso a pessoa aperte o botão cadastrar (Ingrediente)
        //Todos as txt boxes preenchidas, vão ser armazenadas no objeto i da classe Ingrediente
        Ingrediente i = new Ingrediente(
                        new MateriaPrima(
                                txtIngredienteNome.getText(), 
                                txtIngredienteUnidade.getText(), 
                                txtIngredienteFornecedor.getText(), 
                                Float.parseFloat(txtIngredientePreco.getText())
                        ), 
                        Integer.parseInt(txtIngredienteQuant.getText())
                        );
        
        //Adicionando o objeto i na lista de Ingredientes
        listaIngrediente.add(i);
        
        //limpando todas as txt boxes
        txtIngredienteCusto.setText("");
        txtIngredienteFornecedor.setText("");
        txtIngredienteNome.setText("");
        txtIngredientePreco.setText("");
        txtIngredienteQuant.setText("");
        txtIngredienteUnidade.setText("");
        
        // Mostrando uma msg, caso o ingrediente fosse cadastrado
        lblIngredienteCadastroSucess.setText("Ingrediente cadastrado!");

    }//GEN-LAST:event_bttIngredCadActionPerformed

    private void bttManufaturaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttManufaturaCadastrarActionPerformed
        //Caso a pessoa aperte o botão cadastrar (Manufatura)
        //Cadastrando os valores do operador no objeto o da classe Operador
        Operador o = new Operador(txtOpNome.getText(),
            new Data(
                Integer.parseInt(txtOpDiaNasc.getText()),
                Integer.parseInt(txtOpMesNasc.getText()),
                Integer.parseInt(txtOpAnoNasc.getText())
            ),
            txtOpCPF.getText(),
            new Endereco(
                txtEnderecoEstado.getText(),
                txtEnderecoCidade.getText(),
                txtEnderecoBairro.getText(),
                txtEnderecoRua.getText(),
                Integer.parseInt(txtEnderecoNumero.getText())
            ),
            txtCargo.getText(),
            Float.parseFloat(txtSalarioPorHora.getText())
        );
       
        //Cadastrando os valores do Equipamento no objeto e da classe Equipamento
        Equipamento e = new Equipamento(txtNome1.getText(),
            txtFabricante.getText(),
            new Data(Integer.parseInt(txtClienteDiaNasc1.getText()),
                Integer.parseInt(txtClienteMesNasc1.getText()),
                Integer.parseInt(txtClienteAnoNasc1.getText())),
            Float.parseFloat(txtDepreciacao.getText())
        );

        //Passando os objetos com os cadastros salvos no objeto p da classe Processo
        Processo p = new Processo(o, e);
        
        //Setando os valores preenchidos das txts boxes da manufatura no objeto p da classe Processo
        p.setNome(txtManufaturaProcesso.getText());
        p.setCustoHora(Float.parseFloat(txtManufaturaCusto.getText()));
        
        //Passando o objeto p para no objeto m da classe Manufatura
        Manufatura m = new Manufatura(p);
        m.setQtde(Float.parseFloat(txtManufaturaHoras.getText()));
        
        //Adicionando o objeto m da classe Manufatura a lista de Manufaturas
        listaManufatura.add(m);
        
        //Limpando todas as txt boxes
        txtManufaturaProcesso.setText("");
        txtManufaturaHoras.setText("");
        txtCargo.setText("");
        txtEnderecoBairro.setText("");
        txtEnderecoCidade.setText("");
        txtEnderecoEstado.setText("");
        txtEnderecoNumero.setText("");
        txtEnderecoRua.setText("");
        txtOpAnoNasc.setText("");
        txtOpCPF.setText("");
        txtOpDiaNasc.setText("");
        txtOpIdade.setText("");
        txtOpMesNasc.setText("");
        txtOpNome.setText("");
        txtSalarioPorHora.setText("");
        txtNome1.setText("");
        txtFabricante.setText("");
        txtClienteAnoNasc1.setText("");
        txtClienteDiaNasc1.setText("");
        txtClienteMesNasc1.setText("");
        txtManufaturaCusto.setText("");
        txtManufaturaCustoTotal.setText("");
        txtDepreciacao.setText("");
        
        //Msg no frontend para informar a pessoa que a manufatura foi cadastrada
        lblManufaturaCadastroSucess.setText("Manufatura cadastrada!");
        

    }//GEN-LAST:event_bttManufaturaCadastrarActionPerformed

    private void txtCustoDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoDoProdutoActionPerformed
        
    }//GEN-LAST:event_txtCustoDoProdutoActionPerformed

    private void bttCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCalcularActionPerformed
        //Caso a pessoa aperte o botão calcular (Manufatura)  
        //Instanciando os objetos das devidas classes Operador,Equipamento,Manufatura e Processo
        Operador o = new Operador();
        Equipamento e = new Equipamento();
        Manufatura m = new Manufatura();
        Processo p = new Processo(o, e);
        
        // Setando os valores dos objetos, de acordo com os inputs da txt box
        m.setQtde(Float.parseFloat(txtManufaturaHoras.getText()));
        o.setSalarioHora(Float.parseFloat(txtSalarioPorHora.getText()));
        e.setDepreciacaohora(Float.parseFloat(txtDepreciacao.getText()));
        
        // Setando o valor de custo nas txt box, de acordo com os valores dos objetos
        txtManufaturaCusto.setText(String.valueOf(p.calculaCusto()));
        
        //Setando o valor de custo total de acordo com os valores nos inputs das txt boxes
        txtManufaturaCustoTotal.setText(String.valueOf((Float.parseFloat(txtManufaturaCusto.getText()))*(Float.parseFloat(txtManufaturaHoras.getText()))));

    }//GEN-LAST:event_bttCalcularActionPerformed

    private void bttCalcularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bttCalcularFocusLost

    }//GEN-LAST:event_bttCalcularFocusLost

    private void txtIngredienteCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteCalcActionPerformed
        //Caso a pessoa aperte o botão calcular (Ingrediente)  
        //Setando o valor da txt box de Custo de acordo com os inputs preenchidos pelo usuario
        txtIngredienteCusto.setText(String.valueOf((Float.parseFloat(txtIngredientePreco.getText()))*(Integer.parseInt(txtIngredienteQuant.getText()))));
    }//GEN-LAST:event_txtIngredienteCalcActionPerformed

    private void bttCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarProdutoActionPerformed
        //Caso a pessoa aperte o botão cadastrar (Produto)  
        
        //Pegando a txt box preenchida pelo usuario e colocando em uma variavel
        String nome = txtNome.getText();
        
        
        //limpando todas as txt boxes
        txtNome.setText("");
        txtCustoDoProduto.setText("");
        
        //Adicionando as duas listas no objeto pd da classe Produto, juntamente calculando o custo
        Produto pd = new Produto(nome, listaIngrediente, listaManufatura);
        pd.calculaCusto();
        
        //Adicionando o objeto pd da classe Produdo a lista de Produtos
        this.listaProdutos.add(pd);
        
        JOptionPane.showMessageDialog(null, "Produto cadastrado!");
        
        //Mudando de uma interface gráfica para a outra (CadastrarProduto -> Cadastrar), passando as duas listas
        new CadastrarProduto(this.listaPedidos,this.listaProdutos).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bttCadastrarProdutoActionPerformed

    private void txtManufaturaHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufaturaHorasActionPerformed
    }//GEN-LAST:event_txtManufaturaHorasActionPerformed

    private void txtOpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpNomeActionPerformed
    }//GEN-LAST:event_txtOpNomeActionPerformed

    private void txtOpDiaNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpDiaNascActionPerformed
    }//GEN-LAST:event_txtOpDiaNascActionPerformed

    private void txtOpAnoNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOpAnoNascFocusLost
        //Logo após preencher a data de nascimento do Operador, mostrará a idade
        int idade = (LocalDate.now().getYear())- (Integer.parseInt(txtOpAnoNasc.getText()));
        txtOpIdade.setText(String.valueOf(idade));
    }//GEN-LAST:event_txtOpAnoNascFocusLost

    private void txtOpAnoNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpAnoNascActionPerformed

    }//GEN-LAST:event_txtOpAnoNascActionPerformed

    private void txtOpIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpIdadeActionPerformed

    }//GEN-LAST:event_txtOpIdadeActionPerformed

    private void txtOpCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpCPFActionPerformed

    }//GEN-LAST:event_txtOpCPFActionPerformed

    private void txtEnderecoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoEstadoActionPerformed

    }//GEN-LAST:event_txtEnderecoEstadoActionPerformed

    private void txtEnderecoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoNumeroActionPerformed

    }//GEN-LAST:event_txtEnderecoNumeroActionPerformed

    private void txtEnderecoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoCidadeActionPerformed
 
    }//GEN-LAST:event_txtEnderecoCidadeActionPerformed

    private void txtEnderecoRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoRuaActionPerformed

    }//GEN-LAST:event_txtEnderecoRuaActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed


    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtSalarioPorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioPorHoraActionPerformed

    }//GEN-LAST:event_txtSalarioPorHoraActionPerformed

    private void txtClienteDiaNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteDiaNasc1ActionPerformed
    }//GEN-LAST:event_txtClienteDiaNasc1ActionPerformed

    private void txtClienteAnoNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteAnoNasc1ActionPerformed
    }//GEN-LAST:event_txtClienteAnoNasc1ActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed

    }//GEN-LAST:event_txtNome1ActionPerformed

    private void txtDepreciacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepreciacaoActionPerformed
    }//GEN-LAST:event_txtDepreciacaoActionPerformed

    private void txtFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricanteActionPerformed
    }//GEN-LAST:event_txtFabricanteActionPerformed

    private void bttCadastrarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarProduto1ActionPerformed
        //Caso o usuario clique no calcular (produto)
        //É passado a lista de manufatura e a lsita de ingredientes para o objeto p da classe Produto
        Produto p = new Produto(listaManufatura, listaIngrediente);
        
        //Chamando o objeto é possivel calcular o custo e logo depois é setado na box do CustoDoProduto
        p.calculaCusto();
        txtCustoDoProduto.setText(String.valueOf(p.getCusto()));
    }//GEN-LAST:event_bttCadastrarProduto1ActionPerformed

    private void txtIngredienteNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIngredienteNomeFocusGained
        //Tirando a msg de ingrediente cadastrado
        lblIngredienteCadastroSucess.setText("");
    }//GEN-LAST:event_txtIngredienteNomeFocusGained

    private void txtManufaturaProcessoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtManufaturaProcessoFocusGained
        //Tirando a msg de manufatura cadastrada
        lblManufaturaCadastroSucess.setText("");
    }//GEN-LAST:event_txtManufaturaProcessoFocusGained

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        // Para caso as listas estiverem vazias
        if (this.listaIngrediente == null){
            this.listaIngrediente = new ArrayList<>();
        }
        if (this.listaManufatura == null){
            this.listaManufatura = new ArrayList<>();
        }
    }//GEN-LAST:event_txtNomeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCadastrarProduto;
    private javax.swing.JButton bttCadastrarProduto1;
    private javax.swing.JButton bttCalcular;
    private javax.swing.JButton bttIngredCad;
    private javax.swing.JButton bttManufaturaCadastrar;
    private javax.swing.JButton bttVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblIngredienteCadastroSucess;
    private javax.swing.JLabel lblManufaturaCadastroSucess;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtClienteAnoNasc1;
    private javax.swing.JTextField txtClienteDiaNasc1;
    private javax.swing.JTextField txtClienteMesNasc1;
    private javax.swing.JTextField txtCustoDoProduto;
    private javax.swing.JTextField txtDepreciacao;
    private javax.swing.JTextField txtEnderecoBairro;
    private javax.swing.JTextField txtEnderecoCidade;
    private javax.swing.JTextField txtEnderecoEstado;
    private javax.swing.JTextField txtEnderecoNumero;
    private javax.swing.JTextField txtEnderecoRua;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JButton txtIngredienteCalc;
    private javax.swing.JTextField txtIngredienteCusto;
    private javax.swing.JTextField txtIngredienteFornecedor;
    private javax.swing.JTextField txtIngredienteNome;
    private javax.swing.JTextField txtIngredientePreco;
    private javax.swing.JTextField txtIngredienteQuant;
    private javax.swing.JTextField txtIngredienteUnidade;
    private javax.swing.JTextField txtManufaturaCusto;
    private javax.swing.JTextField txtManufaturaCustoTotal;
    private javax.swing.JTextField txtManufaturaHoras;
    private javax.swing.JTextField txtManufaturaProcesso;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtOpAnoNasc;
    private javax.swing.JTextField txtOpCPF;
    private javax.swing.JTextField txtOpDiaNasc;
    private javax.swing.JTextField txtOpIdade;
    private javax.swing.JTextField txtOpMesNasc;
    private javax.swing.JTextField txtOpNome;
    private javax.swing.JTextField txtSalarioPorHora;
    // End of variables declaration//GEN-END:variables
}
